config/routes.rb
Rails.application.routes.draw do
  resources :articles
  
  get 'welcome/home'=> 'welcome#home'
  get 'welcome/about'=>'welcome#about'
  root 'welcome#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles.rb
class Article < ApplicationController
validates:title, :string , :length=>{minumum:5}   
validates:description,:text, :length=>{minumum:10}            
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article,only:[:edit,:update,:show,:destroy]
  def index
    @article=Article.all
  end
  def new
  @article = Article.new
  end
  def show
  end
def destroy
@article.destroy
flash[:notice] = "Article was successfully deleted"
redirect_to articles_path
end
  def edit
  end
  def create
  @article =Article.new(article_params)
  if @article.save
    flash[:notice]="Article was succesfully"
    redirect_to article_path(@article) 
  else 
    render 'new'
  end
  end
def update
if @article.update(article_params)
flash[:notice] = "Article was successfully updated"
redirect_to article_path(@article)
else
render 'edit'
end
end
   private
   def set_article
     @article = Article.find(params[:id])
   end
   def article_params
   params.require(:article).permit(:title, :description)
   end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
            def home
            end
            def about
                        
            end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

<h2>The following errors prevented the article from getting created</h2>

<ul>

<% @article.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

<% end %>

<%= form_for @article do |f| %>

<p>

<%= f.label :title %><br/>

<%= f.text_field :title %>

</p>

<p>

<%= f.label :description %><br/>

<%= f.text_area :description %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<p><%= link_to "Create New Article",new_article_path %></p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
 </tr>
  
  <% @article.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to "Edit" ,edit_article_path(article) %></td>
    <td><%= link_to "Show",article_path(article) %></td>
    <td><%= link_to "Delete",article_path(article) , method: :delete ,data:{confirm:"Are you sure?"} %></td>
  </tr>
  <%end%>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form' %>
<%= link_to "Back to articles" ,articles_path %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>
<%= link_to "Edit this article" ,edit_article_path(@article) %>
<%= link_to "Back to articles listing" ,articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>

<ul>

<li><%= msg %></li>

</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>This is the about page</h1>

 <%link_to 'Home' ,welcome_home_path %>

app/views/welcome/home.html.erb
<h1>welcome to page ozgeee</h1>

<%= link_to 'TestApp' ,articles_path %> | <%= link_to 'About' ,welcome_about_path %>